#!bin/bash
# ASTRID - CB Manager
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Check if the cb-manager is running or not

source ./vars

if [ -f $PIDFILE ]; then
    echo "$COMPONENT started"
else
    echo "$COMPONENT not started"
fi
