#!/bin/bash
# ASTRID - CB Manager
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=cb-manager
export VERSION=master
export PROJECT=astrid
export INSTALLATION_PATH=/opt/$COMPONENT

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export CB_MAN_HOST=0.0.0.0
export CB_MAN_PORT=5000
export CB_MAN_HEARTBEAT_TIMEOUT=5s
export CB_MAN_HEARTBEAT_PERIOD=5min
export CB_MAN_HEARTBEAT_AUTH_EXPIRATION=30min
export CB_MAN_ELASTICSEARCH_ENDPOINT=localhost:9200
export CB_MAN_ELASTICSEARCH_TIMEOUT=20s
export CB_MAN_ELASTICSEARCH_RETRY_PERIOD=1min
export CB_MAN_DEV_USERNAME=cb-manager
# Password: "astrid" hashed in sha256
export CB_MAN_DEV_PASSWORD=9c804f2550e31d8f98ac9b460cfe7fbfc676c5e4452a261a2899a1ea168c0a50
export CB_MAN_LOG_LEVEL=DEBUG
