@uri = {{catalog_agent_uri}}

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": ["id", "actions"],
    "where": {
        "equals": {
            "target": "partner",
            "expr": "cnit"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

< C:\Users\aless\Dropbox (Personal)\work\projects\astrid\gitlab_repositories\framework\platform\cb-manager\db\catalog\agent\packetbeat-cnit.json

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1
