@uri = {{catalog_algorithm_uri}}

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": [],
    "where": {
        "equals": {
            "target": "id",
            "expr": "dos-predictor"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1
