#!/bin/bash
# ASTRID - Kafka
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=kafka
export COMPONENT_DEP=zookeeper
export VERSION=2.6.0
export SCALA_VERSION=2.12
export INSTALLATION_PATH=/opt/$COMPONENT
export SOURCE=${COMPONENT}_$SCALA_VERSION-$VERSION
export FILE=$SOURCE.tgz

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid
export PIDFILE_DEP=$TMP_PATH/$COMPONENT_DEP.pid

export ZOOKEEPER_PORT=2181
export KAFKA_PORT=9092
