#!/bin/bash
# ASTRID - LCP
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Start the lcp

source ./vars

if [ -f $PIDFILE ] ;; then
    echo "Error: $COMPONENT already started"
    echo "Note: to force the start please remove $PIDFILE"
else
    cd $INSTALLATION_PATH
    python3 main.py &
    echo $? > $PIDFILE
fi
