#!/bin/bash
# ASTRID - LCP
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=lcp
export VERSION=master
export PROJECT=astrid
export INSTALLATION_PATH=/opt/$COMPONENT

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export LCP_HOST=0.0.0.0
export LCP_PORT=4000
export LCP_AUTH_MAX_TTL=10min
export LCP_POLYCUBE_HOST=localhost
export LCP_POLYCUBE_PORT=9000
export LCP_POLYCUBE_TIMEOUT=20s
export LCP_DEV_USERNAME=lcp
# Password: "astrid" hashed in sha256
export LCP_DEV_PASSWORD=9c804f2550e31d8f98ac9b460cfe7fbfc676c5e4452a261a2899a1ea168c0a50
export LCP_LOG_LEVEL=DEBUG
