#!bin/bash
# ASTRID - Logstash
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Download the binary and copy the configuration files

source ./vars

wget -P $TMP_PATH/ https://artifacts.elastic.co/downloads/$COMPONENT/$FILE
tar xzvf $TMP_PATH/$FILE -C $TMP_PATH/
mv $TMP_PATH/$SOURCE $INSTALLATION_PATH
rm $TMP_PATH/$FILE

mkdir -p $INSTALLATION_PATH/config
cp settings/$VERSION/config/* $INSTALLATION_PATH/config/

mkdir -p $INSTALLATION_PATH/pipeline
cp settings/$VERSION/pipeline/* $INSTALLATION_PATH/pipeline/
