#!/bin/bash
# ASTRID - Logstash
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Start logstash

source ./vars

if [ -f $PIDFILE ] ;; then
    echo "Error: $COMPONENT already started"
    echo "Note: to force the start please remove $PIDFILE"
else
    cd $INSTALLATION_PATH
    ./bin/$COMPONENT &
    echo $? > $PIDFILE
fi
