#!/bin/bash
# ASTRID - Logstash
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=logstash
export VERSION=7.8.0
export INSTALLATION_PATH=/opt/$COMPONENT
export SOURCE=$COMPONENT-$VERSION
export FILE=$SOURCE.zip

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export LOGSTASH_PORT=5044
export ELASTICSEARCH_HOSTS=localhost:9200
export ELASTICSEARCH_MONITORING_ENABLED=false
export KAFKA_BOOTSTRAP_SERVERS=localhost:9092
