#!bin/bash
# ASTRID - Cubebeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Download the source, build the component and copy the configuration files

source ./vars

git clone https://github.com/$PROJECT-project/$COMPONENT --branch $VERSION $GOPATH/src/gitlab.com/$PROJECT-repositories/$COMPONENT

cd ./$GOPATH/src/gitlab.com/$PROJECT-repositories/$COMPONENT
./build.sh

cp $COMPONENT $INSTALLATION_PATH/
cp settings/$COMPONENT.yml $INSTALLATION_PATH/
