#!bin/bash
# ASTRID - Cubebeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Download the binary and copy the configuration files

source ./vars

wget https://artifacts.elastic.co/downloads/beats/$COMPONENT/$FILE $TMP_PATH/

tar xzvf $TMP_PATH/$FILE
mv $TMP_PATH/$SOURCE $INSTALLATION_PATH
rm $TMP_PATH/$FILE

cp settings/$COMPONENT.yml $INSTALLATION_PATH/
cp settings/config/* $CONFIG_PATH/
