#!bin/bash
# ASTRID - Cubebeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Download the binary and copy the configuration files

source ./vars

git clone https://github.com/$PROJECT-project/$COMPONENT --branch $VERSION $INSTALLATION_PATH



cp settings/$COMPONENT.yml $INSTALLATION_PATH/
cp settings/config/* $CONFIG_PATH/
