#!/bin/bash
# ASTRID - Cubebeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Start cubebeat

source ./vars

if [ -f $PIDFILE ] ; then
    echo "Error: $COMPONENT already started"
    echo "Note: to force the start please remove $PIDFILE"
else
    cd $INSTALLATION_PATH
    ./$COMPONENT &
    echo $? > $PIDFILE
fi
