#!/bin/bash
# ASTRID - Cubebeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

COMPONENT=cubebeat
VERSION=master
PROJECT=astrid
INSTALLATION_PATH=/opt/$COMPONENT

TMP_PATH=/tmp
PIDFILE=$TMP_PATH/$COMPONENT.pid

ELASTICSEARCH_HOSTS=localhost:9200
ELASTICSEARCH_MONITORING_ENABLED=false
LOGSTASH_HOSTS=localhost:5044
