#!/bin/bash
# ASTRID - Cubebeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=cubebeat
export VERSION=master
export PROJECT=astrid
export INSTALLATION_PATH=/opt/$COMPONENT

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export GOPATH=/opt/go

export ELASTICSEARCH_HOSTS=localhost:9200
export ELASTICSEARCH_MONITORING_ENABLED=false
export LOGSTASH_HOSTS=localhost:5044
