apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-broker
  namespace: astrid-kube
spec:
  selector:
    matchLabels:
      app: context-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: context-broker
    spec:
      containers:
      - name: cb-manager
        image: astridproject/cb-manager:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: CB_MAN_HOST
          value: "0.0.0.0"
        - name: CB_MAN_PORT
          value: "5000"
        - name: CB_MAN_HEARTBEAT_TIMEOUT
          value: "1min"
        - name: CB_MAN_HEARTBEAT_PERIOD
          value: "20s"
        - name: CB_MAN_HEARTBEAT_AUTH_EXPIRATION
          value: 5min
        - name: CB_MAN_ELASTICSEARCH_ENDPOINT
          value: "localhost:9200"
        - name: CB_MAN_ELASTICSEARCH_TIMEOUT
          value: "20s"
        - name: CB_MAN_ELASTICSEARCH_RETRY_PERIOD
          value: "1min"
        - name: CB_MAN_DEV_USERNAME
          value: "cb-manager"
        # Password: "astrid" hashed in sha256
        - name: CB_MAN_DEV_PASSWORD
          value: "9c804f2550e31d8f98ac9b460cfe7fbfc676c5e4452a261a2899a1ea168c0a50"
        - name: CB_MAN_LOG_LEVEL
          value: "DEBUG"
        volumeMounts:
        - name: node
          mountPath: /node

      - name: zookeeper
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: localhost
        volumeMounts:
        - name: node
          mountPath: /node

      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service:9092"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        volumeMounts:
        - name: node
          mountPath: /node

      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.8.0
        ports:
        - containerPort: 5144
        env:
        - name: INSTALLATION_PATH
          value: /usr/share/logstash
        - name: ELASTICSEARCH_MONITORING_ENABLED
          value: "false"
        - name: ELASTICSEARCH_HOSTS
          value: "localhost:9200"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "localhost:9092"
        volumeMounts:
          - name: logstash-config
            mountPath: /usr/share/logstash/config/
          - name: logstash-pipeline
            mountPath: /usr/share/logstash/pipeline/
          - name: node
            mountPath: /node

      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 9200
        env:
        - name: INSTALLATION_PATH
          value: /usr/share/elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_MONITORING_ENABLED
          value: "false"
        - name: ELASTICSEARCH_TRANSPORT_TCP_PORT
          value: "9300"
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data/
        - name: node
          mountPath: /node

      # - name: elasticsearch-data-permission-fix
      #   image: busybox
      #   command:
      #   - "sh"
      #   - "-c"
      #   - "/bin/mkdir -p /node/mnt/elasticsearch-data ; /bin/chmod -R 777 /node/mnt/elasticsearch-data"
      #   securityContext:
      #     runAsUser: 0
      #   volumeMounts:
      #   - name: node
      #     mountPath: /node/

      volumes:
      - name: node
        hostPath:
          path: /
      - name: logstash-config
        configMap:
          name: logstash-config
          items:
          - key: log4j2.properties
            path: log4j2.properties
          - key: logstash.yml
            path: logstash.yml
          - key: pipelines.yml
            path: pipelines.yml
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline
          items:
          - key: data.conf
            path: data.conf
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
