apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-broker
  namespace: astrid-kube
spec:
  selector:
    matchLabels:
      app: context-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: context-broker
    spec:
      containers:
      - name: cb-manager
        image: astridproject/cb-manager:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: CB_MAN_HOST
          value: "0.0.0.0"
        - name: CB_MAN_PORT
          value: "5000"
        - name: CB_MAN_HEARTBEAT_TIMEOUT
          value: "1min"
        - name: CB_MAN_HEARTBEAT_PERIOD
          value: "20s"
        - name: CB_MAN_HEARTBEAT_AUTH_EXPIRATION
          value: 5min
        - name: CB_MAN_ELASTICSEARCH_ENDPOINT
          value: "localhost:9200"
        - name: CB_MAN_ELASTICSEARCH_TIMEOUT
          value: "20s"
        - name: CB_MAN_ELASTICSEARCH_RETRY_PERIOD
          value: "1min"
        - name: CB_MAN_DEV_USERNAME
          value: "cb-manager"
        # Password: "astrid" hashed in sha256
        - name: CB_MAN_DEV_PASSWORD
          value: "9c804f2550e31d8f98ac9b460cfe7fbfc676c5e4452a261a2899a1ea168c0a50"
        - name: CB_MAN_LOG_LEVEL
          value: "DEBUG"

      - name: kafka
        image: astridproject/kafka:2.6.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_PORT
          value: "9092"
        - name: ZOOKEEPER_PORT
          value: "2181"

      - name: logstash
        image: astridproject/logstash-central:7.8.0
        ports:
        - containerPort: 5144
        env:
        - name: ELASTICSEARCH_MONITORING_ENABLED
          value: "false"
        - name: ELASTICSEARCH_HOSTS
          value: "localhost:9200"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "localhost:9092"

      - name: elasticsearch
        image: astridproject/elasticsearch:7.8.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 9200
        env:
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_MONITORING_ENABLED
          value: "false"
        - name: ELASTICSEARCH_TRANSPORT_TCP_PORT
          value: "9300"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data/

      initContainers:
      - name: elasticsearch-configuration
        image: busybox
        command: ["sh", "-c", "chmod 777 /mnt/node/mnt/elasticsearch-data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: node
          mountPath: /mnt/node/

      volumes:
      - name: node
        hostPath:
          path: /
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
