#!/bin/bash
# ASTRID - Elasticsearch
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=elasticsearch
export VERSION=7.8.0
export INSTALLATION_PATH=/opt/$COMPONENT
export SOURCE=$COMPONENT-$VERSION
export FILE=$SOURCE-linux-x86_64.tar.gz

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export ELASTICSEARCH_PORT=9200
export ELASTICSEARCH_MONITORING_ENABLED=false
export ELASTICSEARCH_TRANSPORT_TCP_PORT=9300
