@uri = {{data_uri}}

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": [],
    "limit": {
        "from": 1,
        "to": 10
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1
