# @uri = exec-env
# @uri = catalog/agent
# @uri = type/exec-env
# @uri = type/network-link
# @uri = network-link
@uri = connection

# @uri = instance/agent
# @uri = instance/algorithm
# @uri = catalog/algorithm\
# @uri = instance/ebpf-program
# @uri = catalog/ebpf-program
# @uri = data
# @uri = event
# @uri = pipeline

@select = "id"
@operator = reg_exp
@target = network_link_id
@expr = .*

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": [{{select}}],
    "where": {
        "{{operator}}": {
            "target": "{{target}}",
            "expr": "{{expr}}"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

# < db/catalog/agent/cnit/cubebeat.json
# < db/catalog/agent/cnit/dev.json
# < db/catalog/agent/cnit/filebeat.json
# < db/catalog/agent/cnit/logstash.json
# < db/catalog/agent/cnit/metricbeat.json
# < db/catalog/agent/cnit/nprobe.json
# < db/catalog/agent/cnit/packetbeat.json
# < db/catalog/agent/cnit/termux-api.json
# < db/exec-env/type.json
# < db/network-link/type.json
# < db/network-link/data.json
< db/connection.json

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "where": {
        "{{operator}}": {
            "target": "{{target}}",
            "expr": "{{expr}}"
        }
    }
}
