#!bin/bash
# ASTRID - Logstash
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Download the binary amd copy the configuration files

source ./vars

wget https://artifacts.elastic.co/downloads/logstash/$COMPONENT/$FILE $TMP_PATH/
tar xzvf $TMP_PATH/$FILE
mv $TMP_PATH/$SOURCE $INSTALLATION_PATH
rm $TMP_PATH/$FILE

mkdir -p $INSTALLATION_PATH/config
cp settings/config/* $INSTALLATION_PATH/config/*

mkdir -p $INSTALLATION_PATH/pipeline
cp settings/pipeline/* $INSTALLATION_PATH/pipeline/
