@uri = {{instance_agent_uri}}

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": ["id", "actions"],
    "where": {
        "equals": {
            "target": "id",
            "expr": "filebeat"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1
