@uri = {{instance_algorithm_uri}}

GET {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": ["parameters"],
    "where": {
        "equals": {
            "target": "id",
            "expr": "ddos-predictor-1"
        }
    }
}

###

POST {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "id": "ddos-predictor-1",
    "algorithm_catalog_id": "ddos-predictor"
}

###

PUT {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "id": "ddos-predictor-1",
    "operations": {
        "parameters": [
            {
                "id": "frequency",
                "value": "10s"
            }
        ]
    }
}
###

DELETE {{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "where": {
        "equals": {
            "target": "algorithm_catalog_id",
            "expr": "ddos-predictor"
        }
    }
}
