#!/bin/bash
# ASTRID - Metricbeat
# author: Alex Carrega <alessandro.carrega@cnit.it>

export COMPONENT=metricbeat
export VERSION=7.8.0
export INSTALLATION_PATH=/opt/$COMPONENT
export SOURCE=$COMPONENT-$VERSION-linux-x86_64
export FILE=$SOURCE.tar.gz

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export ELASTICSEARCH_HOSTS=localhost:9200
export ELASTICSEARCH_MONITORING_ENABLED=false
export LOGSTASH_HOSTS=localhost:5044
