@uri = {{type_network_link_uri}}

GET http://{{cb_manager_endpoint}}/{{uri}} HTTP/1.1

{
    "select": [],
    "where": {
        "equals": {
            "target": "id",
            "expr": "pnt2pnt"
        }
    }
}

###

POST http://{{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

PUT http://{{cb_manager_endpoint}}/{{uri}} HTTP/1.1

###

DELETE http://{{cb_manager_endpoint}}/{{uri}} HTTP/1.1
