name: Docker Image CI
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: filebeat
            version: 7.8.0
            context: agents/filebeat
            title: Filebeat
            description: Filebeat Docker image with configuration files
            url: https://www.elastic.co/beats/filebeat
            source: https://github.com/astrid-project/astrid-framework/tree/main/agents/filebeat
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: astridproject/${{ matrix.component }}:${{ matrix.version }}
          labels: |
            org.opencontainers.image.title=${{ matrix.title }}
            org.opencontainers.image.description=${{ matrix.description }}
            org.opencontainers.image.url=${{ matrix.url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).html_url }}/tree/${{ github.event.repository.name }}/${{ matrix.context }}
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
